#!/usr/bin/env bash
# configures new Ubuntu machine to install
# nginx using listening port 80 that returns page that
# contains the string `Hello World` when querying at its
# root `/`.
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /var/www/html/index.html

sudo sed -i "s|        |\t|" /etc/nginx/sites-available/default
