#!/usr/bin/env bash
# Script that installs nginx on a new web server
# and creates a custom HTTP header

replace="^\tlocation / {"
new_404="\terror_page 404 /error404.html;\n\n\tlocation / {"
redir="\tlocation /redirect_me {\n\t\treturn 301 \@scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\tlocation / {"
add_header="\tlocation / {\n\t\tadd_header X-Served-By '$HOSTNAME';"

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y nginx
sudo rm /var/www/html/*.html
sudo echo 'Hello World' | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo sed -i "s|$replace|$redir|" /etc/nginx/sites-available/default
sudo sed -i "s|$replace|$new_404|" /etc/nginx/sites-available/default
sudo sed -i "s|$replace|$add_header|" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
